# Generated by Django 5.1.3 on 2024-11-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='alias',
        ),
    ]
