<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='appuser',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
=======
# Generated by Django 5.1.3 on 2024-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='appuser',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
>>>>>>> origin/main
